<?php
/**
 * Implements hook_menu().
 */
function ob_api_menu() {
  $items = array();

  // Module settings
  $items['admin/config/system/openbroadcaster'] = array(
    'title'            => 'OpenBroadcaster API',
    'description'      => 'Manage the settings to connect to the OpenBroadcaster API.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('ob_api_admin_form'),
    'access arguments' => array('administer site configuration'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'ob_api.admin.inc',
  );

  return $items;
}

/**
 * Send a request to the OpenBroadcaster API.
 */
function ob_api_request($controller, $method, $data = NULL) {
  // API url
  $jsonurl = rtrim(variable_get('ob_api_url', 'http://'), '/') . '/api.php';

  // Set POST variables
  $fields = array(
    'c' => $controller,
    'a' => $method,
  );
  if (!is_null($data)) {
    if (isset($data['i'])) {
      $fields['i'] = $data['i'];
    }
    if (isset($data['k'])) {
      $fields['k'] = $data['k'];
    }
    $fields['d'] = json_encode($data);
  }
  $fields_string = http_build_query($fields);

  // Set the url, number of POST vars, POST data
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $jsonurl);
  curl_setopt($ch, CURLOPT_POST, count($fields));
  curl_setopt($ch, CURLOPT_POSTFIELDS, $fields_string);

  // Ignore SSL errors because Nuxalk's is self-certified
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);

  // Return the output to a variable
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);

  // Execute post
  $result = curl_exec($ch);

  // Close connection
  curl_close($ch);

  return $result;
}

/**
 * Log in to the OpenBroadcaster API.
 */
function ob_api_login($throw=false) {
  $data = array(
    'username' => variable_get('ob_api_username', ''),
    'password' => variable_get('ob_api_password', '')
  );
  $login = json_decode(ob_api_request('Account', 'login', $data));
  if (!isset($login->data)) {
    $msg = "Error logging into OpenBroadcaster server. Please check that your server url, username, and password are correct.";
    if ($throw)
      throw new Exception($msg);
    else {
      watchdog('ob_api', $msg, array(), WATCHDOG_ERROR);
      return false;
    }
  }
  return $login;
}
